# app/jira_client.py
import os
import logging
import httpx
import langsmith

logger = logging.getLogger("vulnerability-lifecycle-jira")

@langsmith.traceable(name="create_jira_ticket", run_type="tool")
async def create_jira_block_issue(cve_id: str, package_name: str, domain: str, target_file: str, analysis_text: str) -> str:
    """Dispatches a structured issue payload to Jira Cloud rest/api/2 endpoint 
    to populate a card onto the tenant's Kanban board.
    """
    jira_url = os.environ.get("JIRA_URL", "").strip("/")
    jira_email = os.environ.get("JIRA_EMAIL", "").strip()
    jira_token = os.environ.get("JIRA_API_TOKEN", "").strip()
    project_key = os.environ.get("JIRA_PROJECT_KEY", "").strip()

    # 🔬 PRECISION DIAGNOSTIC GATE
    config_check = {
        "JIRA_URL": jira_url,
        "JIRA_EMAIL": jira_email,
        "JIRA_API_TOKEN": jira_token,
        "JIRA_PROJECT_KEY": project_key
    }
    missing_vars = [key for key, value in config_check.items() if not value]
    
    if missing_vars:
        logger.error(f"Jira integration execution halted: The following environment variables are missing or empty in Python: {missing_vars}")
        return "https://fallback-jira-missing-configurations"

    summary = f"🚨 OneShield BLOCK_ALERT: {cve_id} found in {package_name}"
    
    description = (
        f"h1. 🛡️ OneShield Segregation of Duties (SoD) Compliance Incident\n\n"
        f"*Vulnerability Identifier:* {cve_id}\n"
        f"*Target Software Component:* {package_name}\n"
        f"*Asset Domain Context:* {domain}\n"
        f"*Target Configuration File:* {target_file}\n\n"
        f"h3. 🔬 Agent Reachability & Core Analytical Audit Verdict:\n"
        f"{analysis_text}\n\n"
        f"---- \n"
        f"✍️ *Action Required:* This issue was generated by the OneShield Agent because a critical policy boundary was crossed. "
        f"Senior Engineering or Security Operations Center (SOC) manual multi-signature review is required to unblock this build container pipeline."
    )

    payload = {
        "fields": {
            "project": {"key": project_key},
            "summary": summary,
            "description": description,
            "issuetype": {"name": "Task"}
        }
    }

    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(
                f"{jira_url}/rest/api/2/issue",
                json=payload,
                auth=(jira_email, jira_token),
                headers={
                    "Accept": "application/json",
                    "Content-Type": "application/json"
                }
            )
            
            if response.status_code == 201:
                res_data = response.json()
                issue_key = res_data.get("key")
                issue_url = f"{jira_url}/browse/{issue_key}"
                logger.info(f"Successfully generated physical Jira compliance ticket card: {issue_url}")
                return issue_url
            else:
                logger.error(f"Jira API connection rejected with status code {response.status_code}: {response.text}")
                return f"{jira_url}/secure/Dashboard.jspa"
                
        except Exception as e:
            logger.error(f"Failed execution connection loop targeting Jira backend service boundary: {str(e)}")
            return f"{jira_url}/secure/Dashboard.jspa"