# app/schemas.py
from typing import List, Dict, Any, Literal, Optional
from pydantic import BaseModel, Field

class CodeAnalysisFinding(BaseModel):
    """Normalized data tracking block generated by SAST, OWASP, and DAST Triage workers."""
    finding_id: str = Field(..., description="Unique code or category hash (e.g., JAVA-S2077 or CWE-89)")
    source_engine: str = Field(default="SAST", description="Source analysis engine tag (e.g., SAST, DAST, OWASP, CONTAINER)")
    severity: str = Field(default="HIGH", description="Severity classification (e.g., LOW, MEDIUM, HIGH, CRITICAL)")
    package_name: str = Field(..., description="Impacted framework library, package, or class path")
    target_file_path: str = Field(..., description="Source code or manifest file requiring scanning evaluation")
    line_number: Optional[int] = Field(None, description="Exact code line metric identified by static engine rules")
    raw_payload_snippet: Dict[str, Any] = Field(default_factory=dict, description="Preserved underlying tool telemetry context")

class CodePatchArtifact(BaseModel):
    """Remediation structural payload synthesized by the SAST and OWASP Fixing Advisor agents."""
    target_file_path: str
    original_code_block: str = Field(..., description="Unsafe code snippet or dependency declaration intercepted")
    remediated_code_block: str = Field(..., description="Refactored code snippet passing secure design standards")
    explanation: str = Field(..., description="Technical engineering justification for the patch pattern used")

class HumanInterventionLedger(BaseModel):
    """Tracks state and change ticket metadata for Tier 1 and Tier 2 compliance boundaries."""
    status: str = Field(default="NOT_TRIGGERED", description="Status tracker (NOT_TRIGGERED, PENDING_APPROVAL, APPROVED, REJECTED)")
    jira_ticket_key: Optional[str] = None
    jira_ticket_url: Optional[str] = None
    approver_identity: Optional[str] = None
    approval_timestamp: Optional[str] = None

class AgentState(BaseModel):
    """The unified multi-agent shared ledger handling asynchronous stage data overlaps."""
    # ──> Core Environment Coordinates
    image_sha: str = Field(..., description="Cryptographic image footprint identifier tag")
    domain: str = Field(default="CorporateBank", description="Target business domain or application scope")
    repo_owner: str = Field(default="", description="Target GitHub workspace organization scope")
    repo_name: str = Field(default="", description="Target application source repository name")
    base_branch: str = Field(default="main", description="Target baseline compilation branch timeline")

    # ──> Pillar 1: De-coupled Ingestion Channels (Stage 1)
    raw_sast_results: List[Dict[str, Any]] = Field(default_factory=list, description="Raw ingestion sink for SonarQube/Checkmarx alerts")
    raw_dast_results: List[Dict[str, Any]] = Field(default_factory=list, description="Raw ingestion sink for OWASP ZAP/Burp Suite alerts")
    raw_container_results: List[Dict[str, Any]] = Field(default_factory=list, description="Raw ingestion sink for Trivy/Snyk container alerts")
    
    # ──> Normalized Inter-Agent Ingestion Tracking Slot
    triaged_findings: List[CodeAnalysisFinding] = Field(default_factory=list, description="Unified, cleaned findings schema prepared for code review")

    # ──> Pillar 2: Deep Analysis Telemetry Cache (Stage 2)
    reachability_map: Dict[str, bool] = Field(default_factory=dict, description="Mapping tracking verified exploit loops per finding ID")
    detailed_audit_verdicts: Dict[str, str] = Field(default_factory=dict, description="Comprehensive engineering rationale text generated by the Secure Code Review agent")
    resolution_strategy: str = Field(default="ALLOW_SIGN", description="Strategy decision (ALLOW_SIGN, BLOCK_ALERT, AUTO_PATCH)")

    # ──> Pillar 3 & 4: Mitigation & Governance Tracking (Stage 3)
    proposed_patches: Dict[str, CodePatchArtifact] = Field(default_factory=dict, description="Exact code rewrites generated by specialized fixing advisors")
    governance_gate: HumanInterventionLedger = Field(default_factory=lambda: HumanInterventionLedger(), description="Live compliance audit state tracker")
    
    # ──> Orchestration Tracking Context
    action_log: List[str] = Field(default_factory=list, description="Immutable system state journal tracing agent interactions")
    next_worker: str = Field(default="supervisor", description="State router field directing LangGraph control loops")